/*
 * Copyright (c) 2022. Worldline Global Collect B.V
 */
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'com.worldline.connect.android.example.kotlin.common'

    defaultConfig {
        minSdk 24
        compileSdk = 37
    }

    compileOptions {
        sourceCompatibility java_version
        targetCompatibility java_version
    }

    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_21
        }
    }

    buildFeatures {
        buildConfig = true
    }

    lint {
        abortOnError false
        lintConfig file('lint.xml')
        targetSdk 37
    }

    buildTypes {
        debug {
            buildConfigField "Boolean", "LOGGING_ENABLED", 'true'
        }
        // To disable logging in production, you can set the LOGGING_ENABLED field to false in a release build of your app
        /*
        release {
            buildConfigField "Boolean", "LOGGING_ENABLED", 'false'
        }
        */
    }
    testOptions {
        targetSdk 37
    }
}

dependencies {
    // Kotlin
    implementation libs.kotlinx.coroutines.android
    implementation libs.gson
    // Android X
    implementation libs.core.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.lifecycle.livedata.core.ktx

    // UI
    implementation libs.material

    // Google pay
    implementation libs.play.services.wallet

    // Worldline
    implementation libs.connect.sdk.client.android
}
